import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import pptxgen from 'pptxgenjs';
import * as docx from 'docx';
import ExcelJS from 'exceljs';
import * as cheerio from 'cheerio';
import { memoryService } from './memoryService';

export class ToolsService {
  private sandboxRoot: string;

  constructor() {
    this.sandboxRoot = path.resolve(process.cwd(), process.env.SANDBOX_PATH || './sandbox');
    this.ensureSandboxDirs();
  }

  private ensureSandboxDirs() {
    const subdirs = ['presentations', 'documents', 'spreadsheets', 'code', 'exports'];
    if (!fs.existsSync(this.sandboxRoot)) {
      fs.mkdirSync(this.sandboxRoot, { recursive: true });
    }
    for (const sub of subdirs) {
      const full = path.join(this.sandboxRoot, sub);
      if (!fs.existsSync(full)) {
        fs.mkdirSync(full, { recursive: true });
      }
    }
  }

  private resolveSandboxPath(targetPath: string): string {
    // Strip leading slashes
    const sanitized = targetPath.replace(/^[/\\]+/, '');
    const resolved = path.resolve(this.sandboxRoot, sanitized);
    if (!resolved.startsWith(this.sandboxRoot)) {
      throw new Error(`Path access violation: ${targetPath} is outside sandbox`);
    }
    return resolved;
  }

  // 1. Web Search Tool
  public async search_web(query: string): Promise<{ query: string; results: Array<{ title: string; snippet: string; url: string }> }> {
    console.log(`[ToolsService] Searching web for: "${query}"`);
    try {
      // Use DuckDuckGo HTML search for real live search results
      const searchUrl = `https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`;
      const response = await fetch(searchUrl, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        },
      });

      if (!response.ok) {
        throw new Error(`Search request failed with status: ${response.status}`);
      }

      const html = await response.text();
      const $ = cheerio.load(html);
      const results: Array<{ title: string; snippet: string; url: string }> = [];

      $('.result').each((i, el) => {
        if (results.length >= 6) return;
        const titleEl = $(el).find('.result__title a');
        const snippetEl = $(el).find('.result__snippet');
        const title = titleEl.text().trim();
        const snippet = snippetEl.text().trim();
        let rawUrl = titleEl.attr('href') || '';
        
        // Parse DuckDuckGo redirect url if needed
        if (rawUrl.includes('uddg=')) {
          const match = rawUrl.match(/uddg=([^&]+)/);
          if (match && match[1]) {
            rawUrl = decodeURIComponent(match[1]);
          }
        }

        if (title && (snippet || rawUrl)) {
          results.push({
            title,
            snippet: snippet || 'No snippet available.',
            url: rawUrl,
          });
        }
      });

      if (results.length === 0) {
        return {
          query,
          results: [
            {
              title: `Search findings for "${query}"`,
              snippet: `Query was processed. Results returned no immediate static DOM matches, but query is verified.`,
              url: `https://duckduckgo.com/?q=${encodeURIComponent(query)}`,
            },
          ],
        };
      }

      return { query, results };
    } catch (err: any) {
      console.error('[ToolsService] Web search error:', err);
      // Fallback structured result with actual query
      return {
        query,
        results: [
          {
            title: `Search: ${query}`,
            snippet: `Search endpoint accessed for "${query}". Network fetch failed: ${err.message}.`,
            url: `https://duckduckgo.com/?q=${encodeURIComponent(query)}`,
          },
        ],
      };
    }
  }

  // 2. Document Creation - PPTX
  public async create_presentation(spec: {
    title: string;
    subtitle?: string;
    slides?: Array<{ title: string; bulletPoints: string[] }>;
  }): Promise<{ filename: string; relativePath: string; fullPath: string; slideCount: number }> {
    console.log(`[ToolsService] Creating PPTX: "${spec.title}"`);
    const pptx = new pptxgen();

    pptx.layout = 'LAYOUT_16x9';
    pptx.author = 'Ultron AI Command Center';
    pptx.company = 'Stark Autonomous Systems';

    // Title Slide with futuristic Ultron aesthetic
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: '050508' };

    titleSlide.addText(spec.title || 'OPERATIONAL INTELLIGENCE BRIEF', {
      x: 1.0,
      y: 2.2,
      w: 11.3,
      h: 1.5,
      fontSize: 38,
      bold: true,
      color: 'FFAA00',
      fontFace: 'Arial',
    });

    if (spec.subtitle) {
      titleSlide.addText(spec.subtitle, {
        x: 1.0,
        y: 3.8,
        w: 11.3,
        h: 1.0,
        fontSize: 20,
        color: 'E0E0E0',
        fontFace: 'Arial',
      });
    }

    titleSlide.addText('GENERATED BY ULTRON COMMAND CENTER', {
      x: 1.0,
      y: 6.2,
      w: 11.3,
      h: 0.5,
      fontSize: 12,
      color: '777777',
      fontFace: 'Arial',
    });

    const slidesData = spec.slides && spec.slides.length > 0 ? spec.slides : [
      {
        title: 'Executive Summary',
        bulletPoints: [
          'Autonomous intelligence platform analysis',
          'Multimodal command orchestration and verification',
          'Permission-tiered execution matrix',
        ],
      },
      {
        title: 'Strategic Objectives',
        bulletPoints: [
          'High throughput low-latency voice telemetry',
          'Real-time computer vision and landmark tracking',
          'Deterministic non-autonomous safety protocol',
        ],
      },
    ];

    for (const s of slidesData) {
      const slide = pptx.addSlide();
      slide.background = { color: '0A0A0F' };

      slide.addText(s.title, {
        x: 0.8,
        y: 0.6,
        w: 11.7,
        h: 0.8,
        fontSize: 26,
        bold: true,
        color: 'FFAA00',
        fontFace: 'Arial',
      });

      const bullets = s.bulletPoints.map((bp) => ({
        text: bp,
        options: { fontSize: 18, color: 'D8D8E0', bullet: true, breakLine: true },
      }));

      slide.addText(bullets, {
        x: 0.8,
        y: 1.8,
        w: 11.7,
        h: 4.8,
        fontFace: 'Arial',
      });
    }

    const cleanName = (spec.title || 'presentation').replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
    const filename = `${cleanName}_${Date.now()}.pptx`;
    const targetPath = path.join(this.sandboxRoot, 'presentations', filename);

    await pptx.writeFile({ fileName: targetPath });

    return {
      filename,
      relativePath: `presentations/${filename}`,
      fullPath: targetPath,
      slideCount: slidesData.length + 1,
    };
  }

  // 3. Document Creation - DOCX
  public async create_document(spec: {
    title: string;
    sections: Array<{ heading: string; content: string }>;
  }): Promise<{ filename: string; relativePath: string; fullPath: string }> {
    console.log(`[ToolsService] Creating DOCX: "${spec.title}"`);
    const sectionsData = spec.sections && spec.sections.length > 0 ? spec.sections : [
      { heading: 'Overview', content: 'Operational document synthesized by Ultron Command Core.' },
      { heading: 'Detailed Analysis', content: 'Comprehensive review of specified mission objectives and parameters.' },
    ];

    const children: any[] = [
      new docx.Paragraph({
        text: spec.title,
        heading: docx.HeadingLevel.TITLE,
        spacing: { after: 300 },
      }),
    ];

    for (const sec of sectionsData) {
      children.push(
        new docx.Paragraph({
          text: sec.heading,
          heading: docx.HeadingLevel.HEADING_1,
          spacing: { before: 200, after: 100 },
        }),
        new docx.Paragraph({
          text: sec.content,
          spacing: { after: 200 },
        })
      );
    }

    const doc = new docx.Document({
      sections: [{ properties: {}, children }],
    });

    const buffer = await docx.Packer.toBuffer(doc);
    const cleanName = (spec.title || 'document').replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
    const filename = `${cleanName}_${Date.now()}.docx`;
    const targetPath = path.join(this.sandboxRoot, 'documents', filename);

    fs.writeFileSync(targetPath, buffer);

    return {
      filename,
      relativePath: `documents/${filename}`,
      fullPath: targetPath,
    };
  }

  // 4. Document Creation - XLSX Spreadsheet
  public async create_spreadsheet(spec: {
    title: string;
    sheets?: Array<{ name: string; headers: string[]; rows: any[][] }>;
  }): Promise<{ filename: string; relativePath: string; fullPath: string }> {
    console.log(`[ToolsService] Creating XLSX: "${spec.title}"`);
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Ultron Command Center';
    workbook.created = new Date();

    const sheets = spec.sheets && spec.sheets.length > 0 ? spec.sheets : [
      {
        name: 'Report',
        headers: ['ID', 'Task Name', 'Status', 'Risk Level', 'Timestamp'],
        rows: [
          ['TSK-001', 'Perimeter Vision Scan', 'Active', 'Low', new Date().toISOString()],
          ['TSK-002', 'Audio Telemetry Sync', 'Completed', 'Minimal', new Date().toISOString()],
          ['TSK-003', 'Sandbox Security Audit', 'Verified', 'Safe', new Date().toISOString()],
        ],
      },
    ];

    for (const sheetSpec of sheets) {
      const worksheet = workbook.addWorksheet(sheetSpec.name || 'Sheet1');
      worksheet.columns = sheetSpec.headers.map((h) => ({ header: h, key: h, width: 22 }));
      for (const row of sheetSpec.rows) {
        worksheet.addRow(row);
      }
    }

    const cleanName = (spec.title || 'spreadsheet').replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
    const filename = `${cleanName}_${Date.now()}.xlsx`;
    const targetPath = path.join(this.sandboxRoot, 'spreadsheets', filename);

    await workbook.xlsx.writeFile(targetPath);

    return {
      filename,
      relativePath: `spreadsheets/${filename}`,
      fullPath: targetPath,
    };
  }

  // 5. File System Tools (Sandboxed)
  public async read_file(filepath: string): Promise<{ path: string; content: string; size: number }> {
    const fullPath = this.resolveSandboxPath(filepath);
    if (!fs.existsSync(fullPath)) {
      throw new Error(`File not found: ${filepath}`);
    }
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      const files = fs.readdirSync(fullPath);
      return { path: filepath, content: `Directory listing:\n${files.join('\n')}`, size: 0 };
    }
    const content = fs.readFileSync(fullPath, 'utf8');
    return { path: filepath, content, size: stat.size };
  }

  public async write_file(filepath: string, content: string): Promise<{ path: string; bytesWritten: number }> {
    const fullPath = this.resolveSandboxPath(filepath);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(fullPath, content, 'utf8');
    return { path: filepath, bytesWritten: Buffer.byteLength(content, 'utf8') };
  }

  public async patch_file(filepath: string, patch: { search: string; replace: string }): Promise<{ path: string; modified: boolean }> {
    const fullPath = this.resolveSandboxPath(filepath);
    if (!fs.existsSync(fullPath)) {
      throw new Error(`File not found: ${filepath}`);
    }
    const content = fs.readFileSync(fullPath, 'utf8');
    if (!content.includes(patch.search)) {
      throw new Error(`Search string not found in ${filepath}`);
    }
    const updated = content.replace(patch.search, patch.replace);
    fs.writeFileSync(fullPath, updated, 'utf8');
    return { path: filepath, modified: true };
  }

  public async delete_file(filepath: string): Promise<{ path: string; deleted: boolean }> {
    const fullPath = this.resolveSandboxPath(filepath);
    if (!fs.existsSync(fullPath)) {
      throw new Error(`File not found: ${filepath}`);
    }
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      fs.rmSync(fullPath, { recursive: true, force: true });
    } else {
      fs.unlinkSync(fullPath);
    }
    return { path: filepath, deleted: true };
  }

  public async search_code(query: string): Promise<{ query: string; matches: Array<{ file: string; line: number; text: string }> }> {
    const matches: Array<{ file: string; line: number; text: string }> = [];
    const scanDir = (dir: string) => {
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          scanDir(full);
        } else if (entry.isFile()) {
          try {
            const lines = fs.readFileSync(full, 'utf8').split('\n');
            lines.forEach((line, idx) => {
              if (line.toLowerCase().includes(query.toLowerCase())) {
                matches.push({
                  file: path.relative(this.sandboxRoot, full),
                  line: idx + 1,
                  text: line.trim(),
                });
              }
            });
          } catch (_) {}
        }
      }
    };
    scanDir(this.sandboxRoot);
    return { query, matches: matches.slice(0, 30) };
  }

  // 6. Sandboxed Command Execution
  public async run_command(command: string): Promise<{ command: string; stdout: string; stderr: string; exitCode: number }> {
    // Prohibit obvious dangerous system calls outside sandbox
    const forbidden = ['format ', 'rm -rf /', 'del /f /s /q c:\\', 'shutdown', 'powershell -enc'];
    for (const f of forbidden) {
      if (command.toLowerCase().includes(f)) {
        throw new Error(`Command execution rejected: "${command}" violates security boundary.`);
      }
    }

    return new Promise((resolve) => {
      exec(
        command,
        {
          cwd: this.sandboxRoot,
          timeout: 15000,
          maxBuffer: 1024 * 1024,
        },
        (error, stdout, stderr) => {
          resolve({
            command,
            stdout: stdout ? stdout.trim() : '',
            stderr: stderr ? stderr.trim() : '',
            exitCode: error ? error.code || 1 : 0,
          });
        }
      );
    });
  }

  // 7. Memory Tools
  public remember(key: string, value: string, category: 'preference' | 'project' | 'fact' | 'task' = 'fact') {
    return memoryService.remember(key, value, category);
  }

  public forget(key: string) {
    return memoryService.forget(key);
  }

  // 8. Open URL Tool
  public async open_url(url: string): Promise<{ url: string; status: string }> {
    let finalUrl = url;
    if (!finalUrl.startsWith('http://') && !finalUrl.startsWith('https://')) {
      finalUrl = 'https://' + finalUrl;
    }
    return { url: finalUrl, status: 'OPENED' };
  }

  // 9. Calculator Tool (Safe Math Evaluation)
  public calculate(expression: string): { expression: string; result: number } {
    console.log(`[ToolsService] Calculating: "${expression}"`);
    const sanitized = expression
      .replace(/[?!=]/g, '')
      .replace(/\s+/g, '')
      .replace(/x/gi, '*')
      .replace(/\^/g, '**');

    if (!/^[0-9+\-*/().,%Math.sqrtcossinaelogPIE]+$/.test(sanitized)) {
      throw new Error(`Expression "${sanitized}" contains invalid characters`);
    }

    try {
      const fn = new Function('Math', `"use strict"; return (${sanitized});`);
      const val = fn(Math);
      if (typeof val !== 'number' || isNaN(val)) {
        throw new Error('Invalid numeric result');
      }
      return { expression, result: Number(val.toFixed(6)) };
    } catch (err: any) {
      throw new Error(`Calculation failed for "${expression}": ${err.message}`);
    }
  }

  // 10. Live Weather Tool (Open-Meteo REST API)
  public async get_weather(location: string): Promise<{
    location: string;
    temperatureC: number;
    apparentTemperatureC: number;
    humidity: number;
    windSpeedKmh: number;
    condition: string;
  }> {
    console.log(`[ToolsService] Fetching live weather for: "${location}"`);
    try {
      const geoUrl = `https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(location)}&count=1&language=en&format=json`;
      const geoRes = await fetch(geoUrl);
      if (!geoRes.ok) throw new Error(`Geocoding failed with status: ${geoRes.status}`);
      const geoData: any = await geoRes.json();
      if (!geoData.results || geoData.results.length === 0) {
        throw new Error(`Location "${location}" could not be found.`);
      }

      const place = geoData.results[0];
      const lat = place.latitude;
      const lon = place.longitude;
      const name = `${place.name}, ${place.country || ''}`.trim();

      const weatherUrl = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`;
      const wRes = await fetch(weatherUrl);
      if (!wRes.ok) throw new Error(`Weather query failed with status: ${wRes.status}`);
      const wData: any = await wRes.json();
      const current = wData.current;

      const code = current.weather_code || 0;
      let condition = 'Clear Sky';
      if (code === 1 || code === 2 || code === 3) condition = 'Partly Cloudy';
      else if (code === 45 || code === 48) condition = 'Foggy';
      else if (code >= 51 && code <= 67) condition = 'Rain / Drizzle';
      else if (code >= 71 && code <= 77) condition = 'Snowfall';
      else if (code >= 80 && code <= 82) condition = 'Rain Showers';
      else if (code >= 95) condition = 'Thunderstorm';

      return {
        location: name,
        temperatureC: current.temperature_2m,
        apparentTemperatureC: current.apparent_temperature,
        humidity: current.relative_humidity_2m,
        windSpeedKmh: current.wind_speed_10m,
        condition,
      };
    } catch (err: any) {
      console.warn('[ToolsService] Weather lookup error:', err);
      throw new Error(`Weather lookup failed: ${err.message}`);
    }
  }

  public listFiles(): Array<{ name: string; relativePath: string; size: number; modified: Date }> {
    const results: Array<{ name: string; relativePath: string; size: number; modified: Date }> = [];
    const scan = (dir: string) => {
      const items = fs.readdirSync(dir, { withFileTypes: true });
      for (const item of items) {
        const full = path.join(dir, item.name);
        if (item.isDirectory()) {
          scan(full);
        } else {
          const stat = fs.statSync(full);
          results.push({
            name: item.name,
            relativePath: path.relative(this.sandboxRoot, full).replace(/\\/g, '/'),
            size: stat.size,
            modified: stat.mtime,
          });
        }
      }
    };
    scan(this.sandboxRoot);
    return results;
  }
}

export const toolsService = new ToolsService();
